apiVersion: v1
kind: Namespace
metadata:
  name: heart-disease-prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: heart-disease-prod
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db-service:5432/heart_disease_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: heart-disease-prod
type: Opaque
data:
  # Base64 encoded values: admin / password123
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: cGFzc3dvcmQxMjM=
